/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DespiertoRouteImport } from './routes/despierto'
import { Route as DiarioRouteImport } from './routes/diario'
import { Route as MadrugadaRouteImport } from './routes/madrugada'
import { Route as MananaRouteImport } from './routes/manana'
import { Route as NocheRouteImport } from './routes/noche'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PlanRouteImport } from './routes/plan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DespiertoRoute = DespiertoRouteImport.update({
  id: '/despierto',
  path: '/despierto',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioRoute = DiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const MadrugadaRoute = MadrugadaRouteImport.update({
  id: '/madrugada',
  path: '/madrugada',
  getParentRoute: () => rootRouteImport,
} as any)
const MananaRoute = MananaRouteImport.update({
  id: '/manana',
  path: '/manana',
  getParentRoute: () => rootRouteImport,
} as any)
const NocheRoute = NocheRouteImport.update({
  id: '/noche',
  path: '/noche',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/despierto': typeof DespiertoRoute
  '/diario': typeof DiarioRoute
  '/madrugada': typeof MadrugadaRoute
  '/manana': typeof MananaRoute
  '/noche': typeof NocheRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/despierto': typeof DespiertoRoute
  '/diario': typeof DiarioRoute
  '/madrugada': typeof MadrugadaRoute
  '/manana': typeof MananaRoute
  '/noche': typeof NocheRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/despierto': typeof DespiertoRoute
  '/diario': typeof DiarioRoute
  '/madrugada': typeof MadrugadaRoute
  '/manana': typeof MananaRoute
  '/noche': typeof NocheRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/despierto'
    | '/diario'
    | '/madrugada'
    | '/manana'
    | '/noche'
    | '/onboarding'
    | '/plan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/despierto'
    | '/diario'
    | '/madrugada'
    | '/manana'
    | '/noche'
    | '/onboarding'
    | '/plan'
  id:
    | '__root__'
    | '/'
    | '/despierto'
    | '/diario'
    | '/madrugada'
    | '/manana'
    | '/noche'
    | '/onboarding'
    | '/plan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DespiertoRoute: typeof DespiertoRoute
  DiarioRoute: typeof DiarioRoute
  MadrugadaRoute: typeof MadrugadaRoute
  MananaRoute: typeof MananaRoute
  NocheRoute: typeof NocheRoute
  OnboardingRoute: typeof OnboardingRoute
  PlanRoute: typeof PlanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despierto': {
      id: '/despierto'
      path: '/despierto'
      fullPath: '/despierto'
      preLoaderRoute: typeof DespiertoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario': {
      id: '/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof DiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/madrugada': {
      id: '/madrugada'
      path: '/madrugada'
      fullPath: '/madrugada'
      preLoaderRoute: typeof MadrugadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manana': {
      id: '/manana'
      path: '/manana'
      fullPath: '/manana'
      preLoaderRoute: typeof MananaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noche': {
      id: '/noche'
      path: '/noche'
      fullPath: '/noche'
      preLoaderRoute: typeof NocheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DespiertoRoute: DespiertoRoute,
  DiarioRoute: DiarioRoute,
  MadrugadaRoute: MadrugadaRoute,
  MananaRoute: MananaRoute,
  NocheRoute: NocheRoute,
  OnboardingRoute: OnboardingRoute,
  PlanRoute: PlanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
